"""Agregar campos de programa manual: platform, program_url, rules_md, bounty_table, out_of_scope_notes, safe_harbor

Revision ID: 3f42837d9595
Revises: 0e214bc64cf5
Create Date: 2026-04-10 15:39:17.853689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f42837d9595'
down_revision: Union[str, None] = '0e214bc64cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('platform', sa.String(length=50), nullable=True))
    op.add_column('targets', sa.Column('program_url', sa.String(length=500), nullable=True))
    op.add_column('targets', sa.Column('rules_md', sa.Text(), nullable=True))
    op.add_column('targets', sa.Column('bounty_table', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('targets', sa.Column('out_of_scope_notes', sa.Text(), nullable=True))
    op.add_column('targets', sa.Column('safe_harbor', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('targets', 'safe_harbor')
    op.drop_column('targets', 'out_of_scope_notes')
    op.drop_column('targets', 'bounty_table')
    op.drop_column('targets', 'rules_md')
    op.drop_column('targets', 'program_url')
    op.drop_column('targets', 'platform')
    # ### end Alembic commands ###
