"""add cascade delete to relationships

Revision ID: 9f2400c6a754
Revises: b6f5f45100e5
Create Date: 2026-04-15 15:10:13.986557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2400c6a754'
down_revision: Union[str, None] = 'b6f5f45100e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pending_actions_scan_id_fkey'), 'pending_actions', type_='foreignkey')
    op.drop_constraint(op.f('pending_actions_finding_id_fkey'), 'pending_actions', type_='foreignkey')
    op.create_foreign_key(None, 'pending_actions', 'findings', ['finding_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pending_actions', 'scans', ['scan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pending_actions', type_='foreignkey')
    op.drop_constraint(None, 'pending_actions', type_='foreignkey')
    op.create_foreign_key(op.f('pending_actions_finding_id_fkey'), 'pending_actions', 'findings', ['finding_id'], ['id'])
    op.create_foreign_key(op.f('pending_actions_scan_id_fkey'), 'pending_actions', 'scans', ['scan_id'], ['id'])
    # ### end Alembic commands ###
