"""agregar_campos_h1_completos_target_scope

Revision ID: cf6a3178f2e1
Revises: 3f42837d9595
Create Date: 2026-04-10 23:23:46.288323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf6a3178f2e1'
down_revision: Union[str, None] = '3f42837d9595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scopes', sa.Column('tier', sa.String(length=20), nullable=True))
    op.add_column('targets', sa.Column('introduction_md', sa.Text(), nullable=True))
    op.add_column('targets', sa.Column('disclosure_policy', sa.Text(), nullable=True))
    op.add_column('targets', sa.Column('program_features', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('targets', sa.Column('program_tags', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('targets', sa.Column('response_efficiency_pct', sa.Float(), nullable=True))
    op.add_column('targets', sa.Column('avg_response_hours', sa.Float(), nullable=True))
    op.add_column('targets', sa.Column('avg_triage_hours', sa.Float(), nullable=True))
    op.add_column('targets', sa.Column('avg_bounty_hours', sa.Float(), nullable=True))
    op.add_column('targets', sa.Column('avg_resolution_hours', sa.Float(), nullable=True))
    op.add_column('targets', sa.Column('bounty_tiers', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('targets', sa.Column('active_campaign', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('targets', sa.Column('focus_areas', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('targets', 'bounty_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('bounty_table', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('targets', 'focus_areas')
    op.drop_column('targets', 'active_campaign')
    op.drop_column('targets', 'bounty_tiers')
    op.drop_column('targets', 'avg_resolution_hours')
    op.drop_column('targets', 'avg_bounty_hours')
    op.drop_column('targets', 'avg_triage_hours')
    op.drop_column('targets', 'avg_response_hours')
    op.drop_column('targets', 'response_efficiency_pct')
    op.drop_column('targets', 'program_tags')
    op.drop_column('targets', 'program_features')
    op.drop_column('targets', 'disclosure_policy')
    op.drop_column('targets', 'introduction_md')
    op.drop_column('scopes', 'tier')
    # ### end Alembic commands ###
